app:
  name: "go-gin"
  version: "v1.0.0"
  ip: "0.0.0.0"
  port: "8001"
  env: "prod"
  logsAddress: "./logs/"

mysql:
  name: "tools"
  host: "127.0.0.1"
  port: "3306"
  password: ""
  dbName: "tools"

notion:
  Auth: ""
  cryptoBlockId: ""
  version: "2022-02-22"

